resources:
  - ../../base
images:
  - name: maxpower-frontend
    newTag: dev2
patches:
  - target:
      kind: Deployment
      name: maxpower-frontend
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: maxpower-frontend
      spec:
        replicas: 1
