apiVersion: v1
kind: Service
metadata:
  name: maxpower-frontend
  namespace: maxpower-frontend
spec:
  selector:
    app: maxpower-frontend
  ports:
    - name: http
      port: 80
      targetPort: 4173
  type: ClusterIP
